# Runs this API on port 80
# Runs on docker single daemon (no swarm)
# Make sure the mount volumes match correctly
# This needs the commited nginx.conf (or your own adapted version)

version: '3.7'
services:
  web:
    image: trafex/php-nginx
    ports:
      - "80:8080"
    volumes:
      - ".:/var/www/html:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf"
